services:
  # Administrator service: adminstack
  adminstack:
    build:
      context: adminstack
      dockerfile: Dockerfile
    container_name: adminstack
    hostname: adminstack
    image: app101/adminstack:latest
    networks:
      app101_shared_network: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /home/adminstack/app101
        read_only: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false

  # API service
  app101apipy:
    container_name: app101apipy
    depends_on:
      app101postgres:
        condition: service_healthy
        required: true
    environment:
      APP_ENV: production
      APP101_LOG_FILE: /var/log/app101/app.log
      DATABASE_URL: postgresql://app101:password@app101postgres:5432/app101db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: app101apipy
    image: app101/apipy:latest
    networks:
      app101_shared_network: null
    ports:
      - mode: ingress
        target: 5000
        published: 5000
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: app101_apipy_logs
        target: /var/log/app101
        volume: {}
  
  # Web application service
  app101web:
    container_name: app101web
    depends_on:
      app101apipy:
        condition: service_started
        required: true
      app101postgres:
        condition: service_healthy
        required: true
    environment:
      API_URL: http://localhost:5000
      PORT: 80
    hostname: app101web
    image: app101/web:latest
    ports:
      - mode: ingress
        target: 80
        published: 8080
        protocol: tcp
    networks:
      app101_shared_network: null
    restart: unless-stopped
  
  # PostgreSQL database service
  app101postgres:
    container_name: app101postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    hostname: app101postgres
    image: app101/postgres:latest
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready --dbname postgres --username app101postgres
      timeout: 10s
      interval: 30s
      retries: 5
    ports:
      - mode: ingress
        target: 5432
        published: 5432
        protocol: tcp
    networks:
      app101_shared_network: null
    restart: unless-stopped
    shm_size: "134217728"
    volumes:
      - type: volume
        source: app101_postgres_data
        target: /var/lib/postgresql/data
        volume: {}
  
  # Adminer service for database management
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:5.1.0-standalone
    networks:
      app101_shared_network: null
    restart: unless-stopped
    ports:
      - "8081:8080"

  # sonarqube service:
  sonarqube:
    build:
      context: sonarqube
      dockerfile: Dockerfile
    container_name: sonarqube
    depends_on:
      app101postgres:
        condition: service_healthy
        required: true
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://app101postgres:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: password
    hostname: sonarqube
    image: app101/sonarqube:latest
    networks:
      app101_shared_network: null
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: sonarqube_data
        target: /opt/sonarqube/data
        volume: {}
      - type: volume
        source: sonarqube_extensions
        target: /opt/sonarqube/extensions
        volume: {}
      - type: volume
        source: sonarqube_logs
        target: /opt/sonarqube/logs

  # grafana:
  grafana:
    container_name: grafana
    build:
      context: grafana
      dockerfile: Dockerfile
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
    hostname: grafana
    image: app101/grafana:latest
    networks:
      app101_shared_network: null
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
        volume: {}
      - type: bind
        source: grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true

  # prometheus:
  prometheus:
    container_name: prometheus
    build:
      context: prometheus
      dockerfile: Dockerfile
    environment:
      UNIVERSE_PROMETHEUS_HOST: http://prometheus:9090
      UNIVERSE_PROMETHEUS_PORT_9090: 9090
      USER: prometheus
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9090/metrics"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    hostname: prometheus
    image: app101/prometheus:latest
    networks:
      app101_shared_network: null
    ports:
    - mode: ingress
      target: 9090
      published: 9090
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: volume
      source: prometheus_data
      target: /prometheus
      volume: {}
    
  # jenkins service
  jenkins:
    container_name: jenkins
    build:
      context: jenkins
      dockerfile: Dockerfile
    environment:
      DOCKER_HOST: tcp://docker:2376 
      DOCKER_CERT_PATH: /certs/client 
      DOCKER_TLS_VERIFY: 1 
    depends_on:
      - dind
    hostname: jenkins
    image: app101/jenkins:latest
    networks:
      app101_shared_network: null
    ports:
      - mode: ingress
        target: 8080
        published: 8082
        protocol: tcp
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home 
      - jenkins-docker-certs:/certs/client:ro 

  # dind service
  dind:
    container_name: dind
    hostname: dind
    image: docker:20.10.7-dind
    privileged: true
    networks:
      app101_shared_network: null
    ports:
      - mode: ingress
        target: 2375
        published: 2375
        protocol: tcp
    restart: unless-stopped
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
  
  # gitlab service
  gitlab:
    build:
      context: gitlab
      dockerfile: Dockerfile  
    container_name: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: h0meL@b69
    hostname: gitlab
    image: app101/gitlab:latest
    ports:
      - 80:80
      - 443:443
      - 2222:22
    networks:
      app101_shared_network: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: gitlab_config
        target: /etc/gitlab
        volume: {}
      - type: volume
        source: gitlab_data
        target: /var/opt/gitlab
        volume: {}
      - type: volume
        source: gitlab_logs
        target: /var/log/gitlab
        volume: {}
 
  # elasticsearch:
  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      node.name: ollama-elasticsearch
      xpack.security.enabled: "false"
    hostname: elasticsearch
    image: app101/elasticsearch:latest
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 9200
        published: 9200
        protocol: tcp
    networks:
      app101_shared_network: null
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
        volume: {}

  # filebeat:
  filebeat:
    build:
      context: filebeat
      dockerfile: Dockerfile
    container_name: filebeat
    depends_on:
      elasticsearch:
        condition: service_started
        required: true
    # environment:
    #   ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    #   LOGSTASH_HOST: logstash:5044
    #   KIBANA_HOST: http://kibana:5601
    hostname: filebeat
    image: app101/filebeat:latest
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 5066
        published: 5066
        protocol: tcp
    networks:
      app101_shared_network: null
    volumes:
      - type: volume
        source: app101_apipy_logs
        target: /var/log/app101
        volume: {}

  # logstash:
  logstash:
    build:
      context: logstash
      dockerfile: Dockerfile
    # command:
    #   - -f
    #   - /usr/share/logstash/pipeline/logstash.conf
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_started
        required: true
    environment:
      LS_HEAP_SIZE: 1024m
    hostname: logstash
    image: app101/logstash:local
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 5044
        published: 5044
        protocol: tcp
    networks:
      app101_shared_network: null

  # kibana:
  kibana:
    build:
      context: kibana
      dockerfile: Dockerfile
    container_name: kibana
    depends_on:
      logstash:
        condition: service_started
        required: true
    environment:
      KIBANA_ELASTICSEARCH_URL: http://elasticsearch:9200
    hostname: kibana
    image: app101/kibana:local
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 5601
        published: 5601
        protocol: tcp
    networks:
      app101_shared_network: null

  #mcpserver service
  mcpgitlab:
    build:
      context: mcpgitlab
      dockerfile: Dockerfile
      args:
        GITLAB_API_URL: http://gitlab/api/v4
        GITLAB_PERSONAL_ACCESS_TOKEN: ${GITLAB_PERSONAL_ACCESS_TOKEN:?}
    environment:
      GITLAB_API_URL: http://gitlab/api/v4
      GITLAB_PERSONAL_ACCESS_TOKEN: ${GITLAB_PERSONAL_ACCESS_TOKEN:?}
    image: app101/mcpgitlab:latest
    networks:
      app101_shared_network: null
    container_name: mcpgitlab
    hostname: mcpgitlab
    profiles:
      - mcpgitlab
    restart: always


volumes:
  app101_apipy_logs:
  app101_postgres_data:
  jenkins-data:
  jenkins-docker-certs:
  gitlab_logs:
  gitlab_data:
  gitlab_config:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  grafana_data:
  prometheus_data:
  elasticsearch_data:
  
networks:
  app101_shared_network:
    name: app101_shared_network
    external: false